-- Supabase SQL Editor에서 전체 실행하세요.
create table if not exists public.stickers (
  id bigint generated by default as identity primary key,
  number integer not null unique,
  name text not null,
  status text not null default 'owned' check (status in ('owned','wanted')),
  note text default '',
  created_at timestamptz not null default now()
);

alter table public.stickers enable row level security;

drop policy if exists "public can read stickers" on public.stickers;
create policy "public can read stickers"
on public.stickers for select
to anon, authenticated
using (true);

drop policy if exists "admins can insert stickers" on public.stickers;
create policy "admins can insert stickers"
on public.stickers for insert
to authenticated
with check (true);

drop policy if exists "admins can update stickers" on public.stickers;
create policy "admins can update stickers"
on public.stickers for update
to authenticated
using (true)
with check (true);

drop policy if exists "admins can delete stickers" on public.stickers;
create policy "admins can delete stickers"
on public.stickers for delete
to authenticated
using (true);

-- 예시 데이터
insert into public.stickers (number,name,status) values
(1007,'예시 포켓몬','owned'),
(909,'예시 포켓몬','wanted')
on conflict (number) do nothing;